<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Tsinswreng.CsTreeTest" Version="0.1.1-alpha" />
		<ProjectReference Include="../Tsinswreng.CsSh/Tsinswreng.CsSh.csproj" />
	</ItemGroup>

</Project>
